# Generated by Django 4.0.4 on 2022-05-12 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='exp_date_month',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='exp_date_year',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item.item'),
            preserve_default=False,
        ),
    ]
